Repository madfish-solutions/templewallet-extension, pull requests merged in 2025-05, with the labels that each got.

#1296 TW-1736: Add "beta" property for all analytic events
  src/lib/analytics/use-analytics.hook.ts
Labels: qa approved, EVM

#1297 TW-1737: Gather beta testers addresses
  src/app/atoms/Checkbox.tsx
  src/app/atoms/SettingsCheckbox.tsx
  src/app/templates/CreatePasswordForm/index.tsx
  src/app/templates/SecuritySettings/usage-analytics-settings.tsx
  src/app/templates/enabling-setting.tsx
  src/lib/temple/back/actions.ts
  src/lib/temple/back/main.ts
  src/lib/temple/back/vault/index.ts
  src/lib/temple/front/client.ts
  src/lib/temple/types.ts
Labels: qa approved, EVM

#1299 TW-1738: Feedback modals for beta testing period
  public/_locales/en/messages.json
  src/app/atoms/action-modal/action-modal.tsx
  src/app/icons/base/message.svg
  src/app/layouts/PageLayout/BackupMnemonicOverlay/backup-options-modal.tsx
  src/app/layouts/PageLayout/BackupMnemonicOverlay/index.tsx
  src/app/layouts/PageLayout/FeedbackModal/index.tsx
  src/app/layouts/PageLayout/FeedbackModal/selectors.ts
  src/app/pages/Home/selectors.ts
  src/app/pages/Welcome/Welcome.tsx
  src/app/templates/AppHeader/index.tsx
  src/app/templates/CreatePasswordForm/index.tsx
  src/lib/constants.ts
Labels: qa approved, EVM

#1287 TW-1690: Swap transaction confirmation
  public/_locales/en/messages.json
  public/_locales/en_GB/messages.json
  public/_locales/pt/messages.json
  public/_locales/tr/messages.json
  public/_locales/uk/messages.json
  src/app/pages/Send/index.tsx
  src/app/pages/Swap/constants.ts
  src/app/pages/Swap/form/SwapForm.form.tsx
  src/app/pages/Swap/form/SwapFormInput/SwapFormInput.props.ts
  src/app/pages/Swap/form/SwapFormInput/index.tsx
  src/app/pages/Swap/form/SwapInfoDropdown/index.tsx
  src/app/pages/Swap/form/index.tsx
  src/app/pages/Swap/form/interfaces.ts
  src/app/pages/Swap/index.tsx
  src/app/pages/Swap/modals/ConfirmSwap/TezosContent.tsx
  src/app/pages/Swap/modals/ConfirmSwap/index.tsx
  src/app/pages/Swap/modals/SwapSettings/index.tsx
  src/app/templates/EvmTransactionView/approve-layout/index.tsx
  src/app/templates/ExploreActionButtons/index.tsx
  src/app/templates/TransactionTabs/index.tsx
  src/app/templates/TransactionTabs/tabs/details.tsx
  src/app/templates/TransactionTabs/use-tezos-estimation-form.ts
  src/app/templates/balances-changes-view/index.tsx
  src/app/templates/balances-changes-view/layout.tsx
  src/app/templates/balances-changes-view/types.ts
  src/app/templates/operation-confirmation-card/index.tsx
  src/app/templates/operation-view-layout.tsx
  src/lib/utils/swap.utils.ts
  yarn.lock
Labels: EVM

#1301 TW-1755 Fix displaying a price of a separate EVM token
  src/app/pages/Token/AssetBanner.tsx
Labels: qa approved

#1302 TW-1759: Update high vulnerability package
  yarn.lock
Labels: qa approved, EVM

#1304 TW-1762 Fix infinite scroll context check
  src/app/atoms/visibility-tracking-infinite-scroll.tsx
  src/app/pages/Collectibles/CollectiblesTab/components/CollectiblesTabBase.tsx
Labels: qa approved, EVM

#1305 TW-1765 Fix 'Testnet mode' label location
  src/app/a11y/FadeTransition.tsx
  src/app/layouts/PageLayout/index.tsx
Labels: EVM

#1306 TW-1766: General bug fixes
  src/app/pages/Collectibles/CollectiblesTab/components/evm-meta-loading.ts
  src/app/root-hooks/evm/balances-loading.ts
  src/app/root-hooks/evm/tokens-metadata-loading.ts
  src/app/root-hooks/evm/use-refresh-if-active.ts
Labels: EVM

#1303 TW-1746: Public RPCs usage improvements
  package.json
  src/app/atoms/NetworkLogo.tsx
  src/app/pages/ChainSettings/index.tsx
  src/app/pages/ChainSettings/manage-url-entities-view/edit-modal.tsx
  src/app/pages/ChainSettings/manage-url-entities-view/index.tsx
  src/app/pages/ChainSettings/manage-url-entities-view/item.tsx
  src/app/pages/Unlock/planets-animation/index.tsx
  src/app/templates/EvmTransactionView/approve-layout/index.tsx
  src/app/templates/TransactionTabs/use-evm-estimation-form.ts
  src/app/templates/UrlInput.tsx
  src/app/templates/connect-ledger-modal/utils.tsx
  src/lib/apis/coingecko.ts
  src/lib/balances/hooks.ts
  src/lib/evm/on-chain/balance.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/evm-http-rpc-listener.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/evm-new-block-listener.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/index.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/transfer-events-listeners/erc1155-transfer-events-listener.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/transfer-events-listeners/erc20-transfer-events-listener.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/transfer-events-listeners/erc721-transfer-events-listener.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/transfer-events-listeners/evm-transfer-events-listener.ts
  src/lib/evm/on-chain/evm-transfer-subscriptions/transfer-events-listeners/make-get-transfer-events-listener.ts
  src/lib/evm/on-chain/get-evm-balances-changes/common.utils.mock.ts
  src/lib/evm/on-chain/get-evm-balances-changes/handlers.ts
  src/lib/evm/on-chain/get-evm-balances-changes/index.test.ts
  src/lib/evm/on-chain/get-evm-balances-changes/index.ts
  src/lib/evm/on-chain/metadata.ts
  src/lib/evm/on-chain/transactions/index.test.ts
  src/lib/evm/on-chain/utils/common.utils.ts
  src/lib/images-uri.ts
  src/lib/temple/back/evm-dapp/handlers.ts
  src/lib/temple/back/evm-dapp/utils.ts
  src/lib/temple/back/vault/index.ts
  src/lib/temple/chains-specs.ts
  src/lib/temple/types.ts
  src/lib/types.d.ts
  src/temple/evm/constants.ts
  src/temple/evm/estimate.ts
  src/temple/evm/get-read-only-evm.ts
  src/temple/evm/index.ts
  src/temple/evm/utils.ts
  src/temple/evm/web3-provider.ts
  src/temple/front/evm/ens.ts
  src/temple/front/evm/helpers.ts
  src/temple/front/ready/networks.ts
  src/temple/front/use-block-explorers.ts
  src/temple/networks.ts
  yarn.lock
Labels: EVM

#1308 TW-1770: Wert top-up session id
  src/app/layouts/PageLayout/OnRampOverlay/OnRampOverlay.tsx
  src/app/layouts/PageLayout/OnRampOverlay/OnRampSmileButton/OnRampSmileButton.tsx
  src/app/layouts/PageLayout/OnRampOverlay/utils/getWertLink.util.ts
  yarn.lock
Labels: qa approved
