Repository madfish-solutions/templewallet-extension, pull requests merged in 2025-04, with the labels that each got.

#1281 TW-1709 [EVM] Failed to get gas fee
  src/app/templates/TransactionTabs/use-evm-estimation-form.ts
Labels: qa approved

#1284 TW-1704 [EVM] Optimize API calls for EVM token balances to reduce credit usage (part 1)
  src/app/hooks/listing-logic/use-account-tokens-listing-logic.ts
  src/app/hooks/listing-logic/use-evm-account-tokens-listing-logic.ts
  src/app/hooks/listing-logic/use-evm-balances-loading-state.ts
  src/app/hooks/listing-logic/use-evm-chain-account-tokens-listing-logic.ts
  src/app/root-hooks/evm/balances-loading.ts
  src/app/root-hooks/evm/tokens-exchange-rates-loading.ts
  src/app/root-hooks/evm/use-refresh-if-active.ts
  src/app/root-hooks/index.tsx
  src/app/store/evm/actions.ts
  src/app/store/evm/balances/actions.ts
  src/app/store/evm/balances/epics.ts
  src/app/store/evm/balances/reducers.ts
  src/app/store/evm/balances/selectors.ts
  src/app/store/evm/balances/state.mock.ts
  src/app/store/evm/balances/state.ts
  src/app/store/evm/balances/utils.ts
  src/app/store/evm/reducer.ts
  src/app/store/evm/selectors.ts
  src/app/store/evm/state.mock.ts
  src/app/store/evm/state.ts
  src/app/store/evm/tokens-exchange-rates/actions.ts
  src/app/store/evm/tokens-exchange-rates/reducers.ts
  src/app/store/evm/tokens-exchange-rates/selectors.ts
  src/app/store/evm/tokens-exchange-rates/state.mock.ts
  src/app/store/evm/tokens-exchange-rates/state.ts
  src/lib/apis/temple/endpoints/evm/api.interfaces.ts
  src/lib/balances/hooks.ts
  src/lib/evm/on-chain/balance.ts
  src/lib/temple/back/actions.ts
  src/lib/temple/back/main.ts
  src/lib/temple/back/store.test.ts
  src/lib/temple/back/store.ts
  src/lib/temple/front/client.ts
  src/lib/temple/front/provider.tsx
  src/lib/temple/front/window-is-active-context.ts
  src/lib/temple/types.ts
  src/temple/networks.ts
Labels: EVM

#1285 TW-1712 Update Taquito to the last version
  package.json
  src/app/pages/Delegate/DelegateForm.tsx
  src/app/pages/Home/OtherComponents/BakingSection/BakerBannerWithStake.tsx
  src/app/pages/ManageAssets/ManageCollectibles.tsx
  src/app/templates/SendForm/Form.tsx
  src/lib/fixed-times.ts
  webpack/base.config.ts
  yarn.lock
Labels: qa approved

#1289 TW-1710 Apply a UX solution for the case a user has 0.3 TEZ or less
  public/_locales/en/messages.json
  src/app/layouts/PageLayout/OnRampOverlay/OnRampOverlay.tsx
  src/app/pages/Swap/form/SwapFormInput/index.tsx
  src/app/pages/Swap/form/index.tsx
  src/app/templates/TransactionTabs/tabs/details.tsx
  src/app/toaster.tsx
Labels: qa approved

#1291 TW-1732: Clean up tezos default tokens
  src/app/pages/Home/OtherComponents/Tokens/components/ListItem.tsx
  src/lib/assets/hooks/tokens.ts
  src/lib/assets/known-tokens.ts
Labels: qa approved, EVM

#1293 TW-1741: Remove Alice&Bob provider
  src/app/icons/alice-bob.svg
  src/app/pages/Market/buy-with-credit-card/config.ts
  src/app/pages/Market/buy-with-credit-card/hooks/use-all-crypto-currencies.ts
  src/app/pages/Market/buy-with-credit-card/hooks/use-all-fiat-currencies.ts
  src/app/pages/Market/buy-with-credit-card/hooks/use-buy-with-credit-card-form-submit.ts
  src/app/pages/Market/buy-with-credit-card/hooks/use-one-payment-provider.ts
  src/app/pages/Market/buy-with-credit-card/hooks/use-payment-providers.ts
  src/app/store/buy-with-credit-card/epics.ts
  src/app/store/buy-with-credit-card/reducers.ts
  src/app/store/buy-with-credit-card/selectors.ts
  src/app/store/buy-with-credit-card/state.mock.ts
  src/app/store/buy-with-credit-card/state.ts
  src/app/store/buy-with-credit-card/utils.ts
  src/app/templates/TopUpProviderIcon.tsx
  src/lib/apis/temple/endpoints/alice-bob.ts
  src/lib/apis/temple/index.ts
  src/lib/buy-with-credit-card/top-up-provider-id.enum.ts
  src/lib/icons/fiat.ts
  src/lib/icons/fiat/kzt.png
  src/lib/icons/fiat/uah.svg
  src/lib/icons/index.ts
Labels: EVM

#1294 TW-1720: Optimize api calls for evm token balances part 2
  src/app/root-hooks/evm/use-refresh-if-active.ts
Labels: EVM

#1286 TW-1707: Quick switch modal update
  src/app/atoms/TotalEquity/TotalEquityBase.tsx
  src/app/hooks/use-account-select-shortcut.ts
  src/app/layouts/PageLayout/ShortcutAccountSwitchOverlay/AccountItem.tsx
  src/app/layouts/PageLayout/ShortcutAccountSwitchOverlay/index.tsx
  src/app/layouts/PageLayout/ShortcutAccountSwitchOverlay/selectors.ts
  src/app/templates/AccountsManagement/index.tsx
  src/app/templates/AccountsModalContent/index.tsx
  src/app/templates/SearchField.tsx
Labels: EVM
